# Generated by Django 4.2.2 on 2023-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0003_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateTimeField(),
        ),
    ]
