# Generated by Django 4.2.2 on 2023-06-10 05:45

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0004_alter_borrowing_borrow_date"),
    ]

    operations = [RunPython(func, reverse_func)]
